stages:
  - build-natives
  - build-java

jobs:
  include:
    - stage: build-natives
      name: "Windows MSVC Natives"
      os: windows
      language: cpp
      install:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - travis_retry wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.0-win64-x64.zip 2>>wgeterr.log
        - unzip cmake-3.13.0-win64-x64.zip > /dev/null
        - mv cmake-3.13.0-win64-x64 cmake-install
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - choco install jdk8
        - choco install visualstudio2017buildtools
        - choco install visualstudio2017-workload-vctools
      script: 
        - echo "Building Windows MSVC Natives"
        - cmake --version
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ../org.eclipse.fx.drift/src-native || cat CMakeFiles/CMakeOutput.log
        - ls -al
        - msbuild releng.sln
    - name: "MacOS GCC Natives"
      os: osx
      language: cpp
      install:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - travis_retry wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.0-Darwin-x86_64.tar.gz
        - tar -xvf cmake-3.13.0-Darwin-x86_64.tar.gz > /dev/null
        - mv cmake-3.13.0-Darwin-x86_64 cmake-install
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/CMake.app/Contents/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
      script: 
        - echo "Building MacOS GCC Natives"
        - cmake --version
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ../org.eclipse.fx.drift/src-native || cat CMakeFiles/CMakeOutput.log
        - make
    - name: "Linux GCC Natives"
      os: linux
      language: cpp
      compiler:
        - gcc
      install:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - travis_retry wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.13.0-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.13.0-Linux-x86_64 cmake-install
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}

      before_script:
              #   - pip install cmake
      script:
        - echo "Building Linux GCC Natives"
        - cmake --version
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" ../org.eclipse.fx.drift/src-native || cat CMakeFiles/CMakeOutput.log
        - ls -al
        - make
    - stage: build-java
      name: "Java Build"
      os: linux
      language: java
      script: 
        - echo "executing Maven"
        - mvn --version
